personas = {
    'Persona_1': {'NombreCompleto': 'Rosa Castro', 'Edad': 27, 'Sexo': 'Hombre', 'Grado': 'Informatica', 'Fin': 'Duda',
                  'Hijos': 'No quiere'},
    'Persona_2': {'NombreCompleto': 'Andrés Reyes', 'Edad': 29, 'Sexo': 'Hombre', 'Grado': 'Deporte',
                  'Fin': 'Relacion estable', 'Hijos': 'Si quiere'},
    'Persona_3': {'NombreCompleto': 'Carmen González', 'Edad': 23, 'Sexo': 'Hombre', 'Grado': 'Informatica',
                  'Fin': 'Duda', 'Hijos': 'Si quiere'},
    'Persona_4': {'NombreCompleto': 'Raúl Díaz', 'Edad': 23, 'Sexo': 'Mujer', 'Grado': 'Comercio', 'Fin': 'Duda',
                  'Hijos': 'No quiere'},
    'Persona_5': {'NombreCompleto': 'Silvia Fernández', 'Edad': 30, 'Sexo': 'Mujer', 'Grado': 'Mecanizado',
                  'Fin': 'Nada serio', 'Hijos': 'Duda'},
    'Persona_6': {'NombreCompleto': 'Andrea González', 'Edad': 28, 'Sexo': 'Hombre', 'Grado': 'Deporte', 'Fin': 'Duda',
                  'Hijos': 'No quiere'},
    'Persona_7': {'NombreCompleto': 'Rosa López', 'Edad': 25, 'Sexo': 'Hombre', 'Grado': 'Comercio',
                  'Fin': 'Nada serio', 'Hijos': 'No quiere'},
    'Persona_8': {'NombreCompleto': 'Fernando Rubio', 'Edad': 20, 'Sexo': 'Mujer', 'Grado': 'Mecanizado',
                  'Fin': 'Relacion estable', 'Hijos': 'No quiere'},
    'Persona_9': {'NombreCompleto': 'Rosa Ramírez', 'Edad': 18, 'Sexo': 'Hombre', 'Grado': 'Deporte',
                  'Fin': 'Nada serio', 'Hijos': 'No quiere'},
    'Persona_10': {'NombreCompleto': 'Fernando Rubio', 'Edad': 20, 'Sexo': 'Hombre', 'Grado': 'Deporte', 'Fin': 'Duda',
                   'Hijos': 'Si quiere'},
    'Persona_11': {'NombreCompleto': 'Jorge Herrera', 'Edad': 30, 'Sexo': 'Mujer', 'Grado': 'Informatica',
                   'Fin': 'Relacion estable', 'Hijos': 'Duda'},
    'Persona_12': {'NombreCompleto': 'Verónica Ortiz', 'Edad': 33, 'Sexo': 'Hombre', 'Grado': 'Deporte',
                   'Fin': 'Relacion estable', 'Hijos': 'No quiere'},
    'Persona_13': {'NombreCompleto': 'Clara Rubio', 'Edad': 29, 'Sexo': 'Hombre', 'Grado': 'Comercio',
                   'Fin': 'Relacion estable', 'Hijos': 'Duda'},
    'Persona_14': {'NombreCompleto': 'Andrés Rodríguez', 'Edad': 21, 'Sexo': 'Hombre', 'Grado': 'Deporte',
                   'Fin': 'Relacion estable', 'Hijos': 'No quiere'},
    'Persona_15': {'NombreCompleto': 'Carlos Fernández', 'Edad': 28, 'Sexo': 'Mujer', 'Grado': 'Informatica',
                   'Fin': 'Relacion estable', 'Hijos': 'Si quiere'},
    'Persona_16': {'NombreCompleto': 'Alberto Pérez', 'Edad': 21, 'Sexo': 'Mujer', 'Grado': 'Comercio',
                   'Fin': 'Relacion estable', 'Hijos': 'Duda'},
    'Persona_17': {'NombreCompleto': 'Gloria Sánchez', 'Edad': 21, 'Sexo': 'Mujer', 'Grado': 'Informatica',
                   'Fin': 'Duda', 'Hijos': 'Si quiere'},
    'Persona_18': {'NombreCompleto': 'Andrea Torres', 'Edad': 19, 'Sexo': 'Hombre', 'Grado': 'Informatica',
                   'Fin': 'Nada serio', 'Hijos': 'Duda'},
    'Persona_19': {'NombreCompleto': 'Marta Martínez', 'Edad': 27, 'Sexo': 'Hombre', 'Grado': 'Comercio',
                   'Fin': 'Nada serio', 'Hijos': 'Duda'},
    'Persona_20': {'NombreCompleto': 'Lorena Ortiz', 'Edad': 19, 'Sexo': 'Hombre', 'Grado': 'Informatica',
                   'Fin': 'Duda', 'Hijos': 'Duda'},
    'Persona_21': {'NombreCompleto': 'Pablo Pérez', 'Edad': 20, 'Sexo': 'Hombre', 'Grado': 'Mecanizado',
                   'Fin': 'Nada serio', 'Hijos': 'No quiere'},
    'Persona_22': {'NombreCompleto': 'Hugo Herrera', 'Edad': 22, 'Sexo': 'Hombre', 'Grado': 'Deporte', 'Fin': 'Duda',
                   'Hijos': 'Duda'},
    'Persona_23': {'NombreCompleto': 'Pedro Herrera', 'Edad': 22, 'Sexo': 'Hombre', 'Grado': 'Comercio', 'Fin': 'Duda',
                   'Hijos': 'Duda'},
    'Persona_24': {'NombreCompleto': 'Manuel Rubio', 'Edad': 29, 'Sexo': 'Hombre', 'Grado': 'Deporte', 'Fin': 'Duda',
                   'Hijos': 'No quiere'},
    'Persona_25': {'NombreCompleto': 'Hugo Fernández', 'Edad': 23, 'Sexo': 'Mujer', 'Grado': 'Comercio',
                   'Fin': 'Relacion estable', 'Hijos': 'No quiere'},
    'Persona_26': {'NombreCompleto': 'Cristina Fernández', 'Edad': 31, 'Sexo': 'Hombre', 'Grado': 'Mecanizado',
                   'Fin': 'Duda', 'Hijos': 'Duda'},
    'Persona_27': {'NombreCompleto': 'Rosa Navarro', 'Edad': 33, 'Sexo': 'Hombre', 'Grado': 'Deporte', 'Fin': 'Duda',
                   'Hijos': 'Duda'},
    'Persona_28': {'NombreCompleto': 'Álvaro Fernández', 'Edad': 18, 'Sexo': 'Hombre', 'Grado': 'Deporte',
                   'Fin': 'Duda', 'Hijos': 'Si quiere'},
    'Persona_29': {'NombreCompleto': 'Pedro Rubio', 'Edad': 19, 'Sexo': 'Hombre', 'Grado': 'Comercio',
                   'Fin': 'Relacion estable', 'Hijos': 'No quiere'},
    'Persona_30': {'NombreCompleto': 'Lorena López', 'Edad': 20, 'Sexo': 'Mujer', 'Grado': 'Deporte',
                   'Fin': 'Nada serio', 'Hijos': 'No quiere'},
    'Persona_31': {'NombreCompleto': 'Lorena García', 'Edad': 28, 'Sexo': 'Hombre', 'Grado': 'Deporte', 'Fin': 'Duda',
                   'Hijos': 'No quiere'},
    'Persona_32': {'NombreCompleto': 'Gloria Sánchez', 'Edad': 25, 'Sexo': 'Mujer', 'Grado': 'Mecanizado',
                   'Fin': 'Nada serio', 'Hijos': 'Si quiere'},
    'Persona_33': {'NombreCompleto': 'Andrés Herrera', 'Edad': 25, 'Sexo': 'Hombre', 'Grado': 'Mecanizado',
                   'Fin': 'Nada serio', 'Hijos': 'Si quiere'},
    'Persona_34': {'NombreCompleto': 'Javier Rubio', 'Edad': 20, 'Sexo': 'Mujer', 'Grado': 'Mecanizado',
                   'Fin': 'Relacion estable', 'Hijos': 'Duda'},
    'Persona_35': {'NombreCompleto': 'Jesús Rubio', 'Edad': 20, 'Sexo': 'Hombre', 'Grado': 'Informatica', 'Fin': 'Duda',
                   'Hijos': 'No quiere'},
    'Persona_36': {'NombreCompleto': 'Sara Castro', 'Edad': 20, 'Sexo': 'Hombre', 'Grado': 'Deporte',
                   'Fin': 'Relacion estable', 'Hijos': 'Si quiere'},
    'Persona_37': {'NombreCompleto': 'Natalia Fernández', 'Edad': 32, 'Sexo': 'Hombre', 'Grado': 'Comercio',
                   'Fin': 'Relacion estable', 'Hijos': 'Duda'},
    'Persona_38': {'NombreCompleto': 'Gloria Ortiz', 'Edad': 27, 'Sexo': 'Hombre', 'Grado': 'Informatica',
                   'Fin': 'Nada serio', 'Hijos': 'Si quiere'},
    'Persona_39': {'NombreCompleto': 'Clara Navarro', 'Edad': 24, 'Sexo': 'Mujer', 'Grado': 'Comercio',
                   'Fin': 'Nada serio', 'Hijos': 'Si quiere'},
    'Persona_40': {'NombreCompleto': 'María Reyes', 'Edad': 28, 'Sexo': 'Mujer', 'Grado': 'Mecanizado',
                   'Fin': 'Nada serio', 'Hijos': 'No quiere'},
    'Persona_41': {'NombreCompleto': 'Patricia Castro', 'Edad': 24, 'Sexo': 'Hombre', 'Grado': 'Informatica',
                   'Fin': 'Nada serio', 'Hijos': 'Duda'},
    'Persona_42': {'NombreCompleto': 'Noelia Ramírez', 'Edad': 26, 'Sexo': 'Hombre', 'Grado': 'Informatica',
                   'Fin': 'Nada serio', 'Hijos': 'No quiere'},
    'Persona_43': {'NombreCompleto': 'Óscar López', 'Edad': 32, 'Sexo': 'Hombre', 'Grado': 'Deporte',
                   'Fin': 'Nada serio', 'Hijos': 'No quiere'},
    'Persona_44': {'NombreCompleto': 'Ana Ortiz', 'Edad': 18, 'Sexo': 'Mujer', 'Grado': 'Comercio', 'Fin': 'Duda',
                   'Hijos': 'No quiere'},
    'Persona_45': {'NombreCompleto': 'Víctor Fernández', 'Edad': 27, 'Sexo': 'Hombre', 'Grado': 'Deporte',
                   'Fin': 'Relacion estable', 'Hijos': 'Duda'},
    'Persona_46': {'NombreCompleto': 'Verónica Ramírez', 'Edad': 23, 'Sexo': 'Mujer', 'Grado': 'Comercio',
                   'Fin': 'Relacion estable', 'Hijos': 'Duda'},
    'Persona_47': {'NombreCompleto': 'Lucía Ortiz', 'Edad': 19, 'Sexo': 'Hombre', 'Grado': 'Deporte',
                   'Fin': 'Nada serio', 'Hijos': 'Duda'},
    'Persona_48': {'NombreCompleto': 'Silvia Martínez', 'Edad': 19, 'Sexo': 'Mujer', 'Grado': 'Comercio', 'Fin': 'Duda',
                   'Hijos': 'Si quiere'},
    'Persona_49': {'NombreCompleto': 'Francisco Ortiz', 'Edad': 20, 'Sexo': 'Mujer', 'Grado': 'Mecanizado',
                   'Fin': 'Nada serio', 'Hijos': 'Si quiere'},
    'Persona_50': {'NombreCompleto': 'Lucía Pérez', 'Edad': 22, 'Sexo': 'Mujer', 'Grado': 'Comercio',
                   'Fin': 'Nada serio', 'Hijos': 'Duda'}}